- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copy NGINX config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/{{ domain_name }}
    mode: 0644

- name: Enable NGINX site
  file:
    src: /etc/nginx/sites-available/{{ domain_name }}
    dest: /etc/nginx/sites-enabled/{{ domain_name }}
    state: link
    force: yes

- name: Remove default site (optional)
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Test NGINX config
  command: nginx -t
  register: nginx_test
  changed_when: false

- name: Reload NGINX
  service:
    name: nginx
    state: restarted
  when: nginx_test.rc == 0

- name: Install Certbot
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present
    update_cache: yes

- name: Obtain TLS certificate from Let's Encrypt
  command: >
    certbot --nginx -n --agree-tos --redirect
    --email edj3650@gmail.com
    -d {{ domain_name }}
  args:
    creates: /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem
